In [30]:
from sqlalchemy import create_engine
import pandas as pd
import getpass #para manejo de password seguro en conexion a Mysql

In [32]:
# Verifique los datos de su entorno en MySQL
usuario = "root"
host = "localhost"
puerto = "3306"
nombre_bd = "prueba"

In [33]:
nombre_tabla = "tabla_prueba"
datos = {
    'id':[1, 2, 3, 4, 5], 
    'campo_1': ['hola', 'chau','volvi', 'nuevo','hola'],
    'campo_2':['mundo', 'mundo', 'mundo', 'mundo', 'mundo']
}
df = pd.DataFrame(datos)
df

   id campo_1 campo_2
0   1    hola   mundo
1   2    chau   mundo
2   3   volvi   mundo
3   4   nuevo   mundo
4   5    hola   mundo

In [49]:
try:
    # Esto abrirá un cuadro de texto seguro en Jupyter para escribir la clave
    password = getpass.getpass("Ingrese su contraseña de MySQL: ")    

    # Luego creas el engine normalmente
    engine = create_engine(f"mysql+pymysql://{usuario}:{password}@{host}:{puerto}/{nombre_bd}")
        
    # Ingesta del DataFrame final
    df.to_sql(
        name=nombre_tabla, 
        con=engine, 
        if_exists='replace', # 'replace' borra la tabla y la crea de nuevo. 'append' agrega datos.
        index=False,         # No queremos que el índice de pandas sea una columna en SQL
        chunksize=1000       # Envía los datos en bloques de 1000 para no saturar la memoria
    )
    print(f"✅ ¡Éxito! Datos cargados en la tabla '{nombre_tabla}'.")

except Exception as e:
    print(f"❌ Error al cargar en MySQL: {e}")

# Validamos leyendo directamente desde SQL
df_verificacion = pd.read_sql(f"SELECT COUNT(*) as total_registros FROM {nombre_tabla}", con=engine)
print(f"Registros confirmados en MySQL: {df_verificacion['total_registros'][0]}")
print(f"Primeros 10 registros")
df_consulta = pd.read_sql(f"SELECT * FROM {nombre_tabla} limit 10", con=engine)
df_consulta

Ingrese su contraseña de MySQL:  ········

✅ ¡Éxito! Datos cargados en la tabla 'tabla_prueba'.
Registros confirmados en MySQL: 5
Primeros 10 registros

   id campo_1 campo_2
0   1    hola   mundo
1   2    chau   mundo
2   3   volvi   mundo
3   4   nuevo   mundo
4   5    hola   mundo